# standard settings for charm.py
#  left-hand side should be in JSON synthax
#  int = 1
#  float = 1.2
#  bool = true/false (lower case)
#  str = "string" (double quotes)
#  list = [1, 2, 3]
#  dict = {"a": 1, "b": 2} (key must be string)

[general]
# If threads is 0 the code uses all available threads, otherwise specify a
# positive integer number
threads = 8


[preprocess]
denoise = false


# General settings for running samseg
[samseg]
atlas_name = "charm_atlas_mni_v1-1"

# Custom intensity parameter file (default: empty)
# Note if a file is provided it should be in the same
# folder as the settings.ini file
gmm_parameter_file = "sharedGMMParameters_PETRA.txt"

# Available options
# - atlas   Register an atlas (mesh) to the image (default)
# - mni     Register the T1w MNI template using cross-correlation. See the
#           'initmni'section below for options (only works with T1w images)
# - trega   Use the TREGA network from the brainnet package
init_type = "trega"

# This is the default initialization for the segmentation
# when a T1-weighted input is available
[initmni]
# Translation scales for the optimizer
# (don't change this unless you know what you're doing default 1e-5)
translation_scale = -100
# Maximum number of iterations
max_iter = 300
# Shrink factor for the optimizer defined in 2^f.
# I.e., a shrink factor of 2 corresponds to downsampling
# by 2^2 = 4. Although 1 and 0 are valid inputs, less downsampling
# makes the initialization extremely slow, so not recommended.
shrink_factors = [2, 1, 0]
# A value for filling the background
bg_value = 0
# Smoothing factor for the intensities for optimization (in mm)
smoothing_factors = [4.0, 2.0, 0.0]
# Center-of-mass initialization, if set to zero the geometrical
# center is used instead.
center_of_mass = true
# Random sampling factor of the metric
samp_factor = 1.0
# Number of histogram bins
num_histogram_bins = 64


[initatlas]
# Scaling factors to search through as an initialization default: [0.85, 0.9, 0.95]
affine_scales = [[0.85, 0.85, 0.85], [0.9, 0.9, 0.85], [0.95, 0.95, 0.85]]
# Rotations (around LR axis, degrees) to search through default: [-7, -3.5, 0, 3.5, 7]
affine_rotations = [-7, -3.5, 0, 3.5, 7]
# Horizontal shifts (in mm) to search through default: [-20.0, -10.0, 0, 10.0, 20.0]
affine_horizontal_shifts = [-20.0, -10.0, 0, 10.0, 20.0]
# Vertical shifts to search through (in mm) default: [-10.0, 0.0, 10.0]
affine_vertical_shifts = [-10.0, 0.0, 10.0]
# Neck deformation bounds default: [-0.4, 0.1]
neck_search_bounds = [-0.3, 0.1]
# Downsampling target resolution (in mm) default: 2
downsampling_factor_affine = 2

[segment]
# Downsampling target resolution in mm default [2.0, 1.0]
downsampling_targets = [2.0, 1.0]
# Kernel size of bias field basis functions (in mm),
# smaller kernels are more flexible default: 70
bias_kernel_width = 70
# Smoothing factor for background mask in mm default: 4.0
background_mask_sigma = 4.0
# Threshold for masking background away default: 0.001
background_mask_threshold = 0.001
# Deformation penalty on the seg mesh  default: 0.1
mesh_stiffness = 0.1
# How to model Gaussian when multimodal data default: false
diagonal_covariances = false
# Downweighing factor for CSF when using T1+T2
csf_factor = 0.3

[surfaces]
# Topofit settings
# valid contrast/resolution combinations:
#   (T1w, 1mm), (synth, 1mm), (synth, random)
topofit_contrast = "T1w"
topofit_resolution = "1mm"
topofit_device = "cpu"

# Parameters for central surface estimation
# float in range [0, 1.0]
central_surface_fraction = 0.5
# equidistance, equivolume, linear fit model?
central_surface_method = "equivolume"

# Use the estimated cortical surfaces to update the segmentation
update_segmentation_from_surfaces = true

# When updating the segmentation from the estimated cortical surfaces, protect
# these structures from relabeling (labels refer to those in the `labeling`
# image, i.e., the FreeSurfer labels).
#
#   1. GM outside pial surface to CSF
#   2. WM outside WM surface to GM
#   3. GM inside WM surface to WM
#   4. CSF inside pial surface to GM
#   5. CSF inside WM surface to WM (this uses the union of csf_to_gm and gm_to_wm)
update_segmentation_protect = {
    "gm_to_csf": [
        "Left-Cerebellum-White-Matter",
        "Left-Cerebellum-Cortex",
        "Left-Hippocampus",
        "Left-Amygdala",
        "Right-Cerebellum-White-Matter",
        "Right-Cerebellum-Cortex",
        "Right-Hippocampus",
        "Right-Amygdala",
        "Optic-Chiasm",
        "Optic-Nerve"
    ],
    "wm_to_gm": [
        "Left-Cerebellum-White-Matter",
        "Left-VentralDC",
        "Right-Cerebellum-White-Matter",
        "Right-VentralDC",
        "Brain-Stem",
        "Optic-Chiasm",
        "Spinal-Cord",
        "Optic-Nerve"
    ],
    "gm_to_wm": [
        "Left-Thalamus-Proper",
        "Left-Caudate",
        "Left-Putamen",
        "Left-Pallidum",
        "Left-Hippocampus",
        "Left-Amygdala",
        "Left-Accumbens-area",
        "Right-Thalamus-Proper",
        "Right-Caudate",
        "Right-Putamen",
        "Right-Pallidum",
        "Right-Hippocampus",
        "Right-Amygdala",
        "Right-Accumbens-area"
    ],
    "csf_to_gm": [
        "Left-Lateral-Ventricle",
        "Left-Inf-Lat-Vent",
        "Left-choroid-plexus",
        "Right-Lateral-Ventricle",
        "Right-Inf-Lat-Vent",
        "Right-choroid-plexus"
    ]}

# The number of workers to use for the spherical registration. Select one for
# sequential and two for parallel processing of hemispheres.
spherical_registration_process_pool = 2

[mesh]
# Define thickness-dependent element sizes
# 	"range": upper and lower cut-offs for element sizes (in mm)
# 	"slope": the smaller the finer the mesh
# 	"standard": applies to all tissues not defined otherwise
elem_sizes = {"standard": {"range": [1, 5], "slope": 1.0},
                     "1": {"range": [1, 7], "slope": 1.0},
                     "2": {"range": [1, 2], "slope": 1.0},
                     "5": {"range": [1, 10], "slope": 0.6}}
# Size of triangular kernel to smooth the size field. Can be 0.
smooth_size_field = 2
# Maximum size for the triangles of the outermost surface (in mm).
# 	Set to false to apply the same scaling as for the other elements.
skin_facet_size = 2.0
# Relation between thickness and maximally allowed distance of
# boundary facets to "true" label boundary (in mm)
# 	"range": upper and lower cut-offs for the boundary facet distances
# 	"slope": the smaller the better the mesh follows the segmentation
facet_distances = {"standard": {"range": [0.1, 3], "slope": 0.5}}
# Whether to optimize the mesh using sliver perturbation, exudation, and Lloyd
# optimization. By default, this is not done as we rely on MMG to optimize the
# tetrahedral mesh instead.
optimize = false
# Whether to apply a cream layer around the head to improve results of spike removal
apply_cream = true
# Whether to remove spikes from the mesh to create smoother mesh surfaces
remove_spikes = true
# Add outer surface to mesh using given tag. Set to false to disable.
skin_tag = 1005
# Hierarchy of surface tags (as list) that determines which triangle
# of a twin pair is kept. Set to false to use standard.
hierarchy = false
# Number of smoothing steps applied to the final surfaces. Can be 0.
smooth_steps = 10
# Number of addtional smoothing steps applied to the skin. Can be 0.
skin_care = 20
# If True, no additional points will be inserted into the mesh during mesh quality improvement step (not recommended)
mmg_noinsert = false

